[Node 50: DB-API 2.0 SQL-Anbindungen](http://www-static.etp.physik.uni-muenchen.de/kurs/Computing/python2/node50.html)

Navigation:

**Next:** [SQLite mit sqlite3](node51.ipynb) **Up:** [SQLite mit sqlite3](node51.ipynb) **Previous:** [SQLite mit sqlite3](node51.ipynb)

## DB API 2.0 SQL connections
Relational databases are usually controlled with SQL.
* Relational Database: Collection of tables in which records are stored with unique keys.
* SQL: Structured Query Language, database language for defining, querying and manipulating data in relational databases
* Known databases: SQLite, PostgreSQL, MySQL, Oracle,...
* With DB-API 2.0 different DBs can be addressed with the same look-and-feel

Code fragment how to connect to a DB, create a table, write and read it again:

```python
# nur zur Illustration, code laeuft nicht
import dbapi
conn = dbapi.connect(dbname='dbase', host='db.example.com',
                     user='dbuser', password='pw')
curs = conn.cursor()
curs.execute('CREATE TABLE atable ( A INT, B VARCHAR(5) )')
curs.execute('INSERT INTO atable VALUES (%s, %s)', (42, 'ABCDE'))
curs.execute('INSERT INTO atable VALUES (%s, %s)', (4711, 'ZZZZZ'))
conn.commit()
conn.close()
curs.execute('SELECT * FROM atable ORDER BY A')
tpl. curs.fetchone()
while tpl is not None:
    print ("A", tpl[0], "B", tpl[1])
    tpl.curs.fetchone()
```